# Calculation of LU Decomposition
--------------------------------------------------------------------------------------------------

Useful References:
- [wikipedia - LU decomposition](https://en.wikipedia.org/wiki/LU_decomposition)

In [1]:
import numpy as np
from time import time
from scipy.linalg import lu

### Read input file: 
--------------------------------------------------------------------------------------------------
Read matrix from **data_10.txt** and convert it to numpy array.

In [2]:
inputMatrix = np.genfromtxt("data_10.txt", dtype= float, delimiter=",")

In [3]:
print(f'InputMatrix = \n{inputMatrix}')

InputMatrix = 
[[5.18800e-01 5.14200e-01 6.15600e-01 ... 1.47100e-01 6.92000e-02
  3.09000e-02]
 [5.14200e-01 6.97900e-01 7.43700e-01 ... 3.22800e-01 2.32300e-01
  1.28800e-01]
 [6.15600e-01 7.43700e-01 9.60000e-01 ... 3.15400e-01 2.67800e-01
  1.94400e-01]
 ...
 [1.47100e-01 3.22800e-01 3.15400e-01 ... 9.48794e+01 5.83988e+01
  3.36410e+01]
 [6.92000e-02 2.32300e-01 2.67800e-01 ... 5.83988e+01 7.02466e+01
  3.38139e+01]
 [3.09000e-02 1.28800e-01 1.94400e-01 ... 3.36410e+01 3.38139e+01
  4.56111e+01]]


### LU decomposition of the scipy Linear algebra
--------------------------------------------------------------------------------------------------

In [11]:
start = time()
P, L, U = lu(inputMatrix)
print(f'Total Time Taken = {time() - start} sec')

Total Time Taken = 0.11765551567077637 sec


In [5]:
print(f'P = \n{P}\n')
print(f'L = \n{L}\n')
print(f'U = \n{U}')

P@L@U

P = 
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

L = 
[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.88294279  1.          0.         ...  0.          0.
   0.        ]
 [ 0.7957759  -0.50806557  1.         ...  0.          0.
   0.        ]
 ...
 [ 0.01443284  0.01578783  0.0155141  ...  1.          0.
   0.        ]
 [ 0.0262328  -0.01073167  0.02852651 ...  0.67669537  1.
   0.        ]
 [ 0.0224246   0.04076155  0.01312292 ... -0.88798463 -0.00615127
   1.        ]]

U = 
[[ 36.5001      44.8122      52.6052     ...  46.46        32.5423
   18.6102    ]
 [  0.          -0.83400874   0.18071813 ... -11.67462186  -8.21398904
   -4.67844184]
 [  0.           0.           1.17986618 ...  16.07707816  11.02467683
    6.37609608]
 ...
 [  0.           0.           0.         ...   3.94081679   1.36959568
    5.09150392]
 [  0.           0.       

array([[5.18800e-01, 5.14200e-01, 6.15600e-01, ..., 1.47100e-01,
        6.92000e-02, 3.09000e-02],
       [5.14200e-01, 6.97900e-01, 7.43700e-01, ..., 3.22800e-01,
        2.32300e-01, 1.28800e-01],
       [6.15600e-01, 7.43700e-01, 9.60000e-01, ..., 3.15400e-01,
        2.67800e-01, 1.94400e-01],
       ...,
       [1.47100e-01, 3.22800e-01, 3.15400e-01, ..., 9.48794e+01,
        5.83988e+01, 3.36410e+01],
       [6.92000e-02, 2.32300e-01, 2.67800e-01, ..., 5.83988e+01,
        7.02466e+01, 3.38139e+01],
       [3.09000e-02, 1.28800e-01, 1.94400e-01, ..., 3.36410e+01,
        3.38139e+01, 4.56111e+01]])

### Our Implementation For LU Decomposition
--------------------------------------------------------------------------------------------------
- This is LU decomposition with pivoted

In [6]:
def LU_decomposition(A):
    
    #Get the number of rows
    n = A.shape[0]
    
    #Allocate space for P, L, and U
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    P = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
        
        #Permute rows if needed
        for k in range(i, n): 
            if ~np.isclose(U[i, i], 0.0):
                break
            U[[k, k+1]] = U[[k+1, k]]
            P[[k, k+1]] = P[[k+1, k]]
            
        #Eliminate entries below i with row 
        #operations on U and #reverse the row 
        #operations to manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return P, L, U

In [7]:
start = time()
p, l, u = LU_decomposition(inputMatrix)
print(f'Total Time Taken = {time() - start} sec')

Total Time Taken = 13.484934568405151 sec


In [8]:
print(f'P = \n{p}\n')
print(f'L = \n{l}\n')
print(f'U = \n{u}')
l@u

P = 
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

L = 
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.99113338 1.         0.         ... 0.         0.         0.        ]
 [1.18658443 0.70943826 1.         ... 0.         0.         0.        ]
 ...
 [0.28353894 0.94021576 0.11336252 ... 1.         0.         0.        ]
 [0.13338473 0.86961784 0.51595146 ... 0.46476345 1.         0.        ]
 [0.05956052 0.52148299 0.65351992 ... 0.27599314 0.37433931 1.        ]]

U = 
[[ 5.18800000e-01  5.14200000e-01  6.15600000e-01 ...  1.47100000e-01
   6.92000000e-02  3.09000000e-02]
 [ 0.00000000e+00  1.88259214e-01  1.33558288e-01 ...  1.77004279e-01
   1.63713570e-01  9.81739784e-02]
 [ 0.00000000e+00  0.00000000e+00  1.34787268e-01 ...  1.52798237e-02
   6.95436881e-02  8.80861651e-02]
 ...
 [-2.58671653e-15 -3.82926890e-16  8.17218387e-17 ...  2.783944

array([[5.18800e-01, 5.14200e-01, 6.15600e-01, ..., 1.47100e-01,
        6.92000e-02, 3.09000e-02],
       [5.14200e-01, 6.97900e-01, 7.43700e-01, ..., 3.22800e-01,
        2.32300e-01, 1.28800e-01],
       [6.15600e-01, 7.43700e-01, 9.60000e-01, ..., 3.15400e-01,
        2.67800e-01, 1.94400e-01],
       ...,
       [1.47100e-01, 3.22800e-01, 3.15400e-01, ..., 9.48794e+01,
        5.83988e+01, 3.36410e+01],
       [6.92000e-02, 2.32300e-01, 2.67800e-01, ..., 5.83988e+01,
        7.02466e+01, 3.38139e+01],
       [3.09000e-02, 1.28800e-01, 1.94400e-01, ..., 3.36410e+01,
        3.38139e+01, 4.56111e+01]])

### Check the LU Decomposition result.
--------------------------------------------------------------------------------------------------

In [9]:
np.allclose(inputMatrix, p@l@u)

True